blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://authverse.abdirahmandev.com
    about: "Read the official documentation for installation and setup"

  - name: Discussions
    url: https://github.com/abdirahmanmahamoud/authverse/discussions
    about: "Ask questions or suggest ideas here"

  - name: Troubleshooting Guide
    url: https://authverse.abdirahmandev.com/docs/troubleshooting
    about: "Common errors and how to fix them"
